name: Update Requirements

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-requirements:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.2'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update requirements.txt
        run: pip freeze > requirements.txt

      - name: Commit updated requirements.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add requirements.txt
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Update requirements.txt"
            git push origin main
          fi
